services:
  bot:
    image: ghcr.io/igorstarega/bot-muzyczny-2:latest
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config:/app/config:rw
      - ./data:/app/data:rw
